const crypto=require("crypto");
const {neon}=require("@neondatabase/serverless");
function sameSecret(value,expected){const a=Buffer.from(String(value||""));const b=Buffer.from(String(expected||""));return a.length===b.length&&crypto.timingSafeEqual(a,b);}
function csv(value){return `"${String(value??"").replace(/"/g,'""')}"`;}
module.exports=async function handler(req,res){
  res.setHeader("Cache-Control","no-store");
  if(req.method!=="POST")return res.status(405).json({ok:false,error:"Method not allowed."});
  if(!process.env.DATABASE_URL||!process.env.ADMIN_PASSWORD)return res.status(503).json({ok:false,error:"Admin export setup is not complete."});
  if(!sameSecret(req.body?.password,process.env.ADMIN_PASSWORD))return res.status(401).json({ok:false,error:"Incorrect admin password."});
  const from=String(req.body?.fromDate||"");const to=String(req.body?.toDate||"");const name=String(req.body?.clientName||"").trim();
  if(!/^\d{4}-\d{2}-\d{2}$/.test(from)||!/^\d{4}-\d{2}-\d{2}$/.test(to)||from>to)return res.status(400).json({ok:false,error:"Choose a valid date range."});
  try{
    const sql=neon(process.env.DATABASE_URL);await sql`ALTER TABLE visit_submissions ADD COLUMN IF NOT EXISTS arrival_time TIME`;await sql`ALTER TABLE visit_submissions ADD COLUMN IF NOT EXISTS departure_time TIME`;await sql`ALTER TABLE visit_submissions ADD COLUMN IF NOT EXISTS client_first_name TEXT`;await sql`ALTER TABLE visit_submissions ADD COLUMN IF NOT EXISTS client_last_name TEXT`;await sql`ALTER TABLE visit_submissions ADD COLUMN IF NOT EXISTS arrival_guardian_name TEXT`;await sql`ALTER TABLE visit_submissions ADD COLUMN IF NOT EXISTS departure_guardian_name TEXT`;await sql`UPDATE visit_submissions SET arrival_time=visit_time WHERE arrival_time IS NULL`;await sql`UPDATE visit_submissions SET client_first_name=COALESCE(client_first_name,split_part(regexp_replace(TRIM(client_name),'[[:space:]]+',' ','g'),' ',1)),client_last_name=COALESCE(client_last_name,CASE WHEN regexp_replace(TRIM(client_name),'[[:space:]]+',' ','g') LIKE '% %' THEN substring(regexp_replace(TRIM(client_name),'[[:space:]]+',' ','g') FROM position(' ' IN regexp_replace(TRIM(client_name),'[[:space:]]+',' ','g'))+1) ELSE '' END),arrival_guardian_name=COALESCE(arrival_guardian_name,parent_name)`;let rows;
    if(name){rows=await sql`SELECT client_name,client_first_name,client_last_name,arrival_guardian_name,departure_guardian_name,visit_date,COALESCE(arrival_time,visit_time) AS arrival_time,departure_time FROM visit_submissions WHERE visit_date BETWEEN ${from}::date AND ${to}::date AND (LOWER(TRIM(client_name))=LOWER(${name}) OR LOWER(TRIM(arrival_guardian_name))=LOWER(${name}) OR LOWER(TRIM(departure_guardian_name))=LOWER(${name})) ORDER BY visit_date,COALESCE(arrival_time,visit_time)`;}
    else{rows=await sql`SELECT client_name,client_first_name,client_last_name,arrival_guardian_name,departure_guardian_name,visit_date,COALESCE(arrival_time,visit_time) AS arrival_time,departure_time FROM visit_submissions WHERE visit_date BETWEEN ${from}::date AND ${to}::date ORDER BY visit_date,COALESCE(arrival_time,visit_time)`;}
    const lines=[["Client First Name","Client Last Name","Client Full Name","Drop-off Parent or Guardian","Pickup Parent or Guardian","Visit Date","Drop-off Time","Pickup Time"].map(csv).join(","),...rows.map(row=>[row.client_first_name,row.client_last_name,row.client_name,row.arrival_guardian_name,row.departure_guardian_name,row.visit_date,row.arrival_time,row.departure_time].map(csv).join(","))];
    res.setHeader("Content-Type","text/csv; charset=utf-8");res.setHeader("Content-Disposition",`attachment; filename="sos-visits-${from}-to-${to}.csv"`);res.setHeader("X-Visit-Count",String(rows.length));return res.status(200).send("\uFEFF"+lines.join("\r\n"));
  }catch(error){console.error("Visit export failed",{name:error?.name||"Error"});return res.status(500).json({ok:false,error:"Report could not be created. Please try again."});}
};
